# テキスト関連
APP_TITLE = "KagamiDALLE"
CHAT_INPUT_HINT_TEXT = "何か入力してみてください。"
NOT_INPUT_ERROR_TEXT = "プロンプトを入力してからEnterキーを押してください。"
RUN_MODE_LABEL = "動作モード(dall-e-2のみ変更可能)"
MODEL_ID_LABEL = "モデル"
SIZE_LABEL = "サイズ"
QUALITY_LABEL = "生成画像の質(dall-e-3のみ)"
NUM_GEN_LABEL = "生成枚数"
GEN_ERROR_HEAD_TEXT = "画像生成に失敗しました。"
GEN_ERROR_MSG_TEXT = "エラーメッセージ："
CALC_ERROR_TEXT = "為替情報の取得に失敗"
PRICE_TEXT = "生成にかかった料金："
PRICE_EXTENTION = "円"